---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dev-app
  name: dev-app
  namespace: dev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
        - name: dev-app
          image: DockerUser/sample-web:TagVersion
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "200m" 
      restartPolicy: Always
      //imagePullSecrets:
      //- name: regcred
