apiVersion: v1
kind: Service
metadata:
  labels:
    app: stg-app
    role: ingress
  name: stg-app-service
  namespace: stg-ns
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80  
  selector:
    app: stg-app
